"""Curator resources API endpoints."""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.concurrency import run_in_threadpool

from backend.api.schemas.common import ErrorResponse, SuccessResponse
from backend.domains.curator.api.auth import get_current_curator_user
from backend.domains.curator.schemas.resources import (
    CuratorResourceBookmarkRequest,
    CuratorResourceEngagementResponse,
    CuratorResourceOpenRequest,
    CuratorResourcePreferences,
    CuratorResourcePreferencesRequest,
    CuratorResourcesResponse,
)
from backend.domains.curator.workflows.resource_service import CuratorResourceService
from backend.domains.curator.workflows.auth_service import AuthenticatedUser
from backend.domains.curator.workflows.growth_journey_service import CuratorGrowthJourneyService
from backend.domains.curator.workflows.identity_profile_persistence_service import IdentityProfilePersistenceService
from backend.framework.agents.base_agent import TransientLLMError


logger = logging.getLogger(__name__)
router = APIRouter(prefix="/curator/resources", tags=["curator"])


def get_curator_resource_service(
    auth_user: AuthenticatedUser = Depends(get_current_curator_user),
) -> CuratorResourceService:
    """Return the Curator resource service dependency."""

    identity_service = IdentityProfilePersistenceService(user_id=auth_user.user.id)
    return CuratorResourceService(
        identity_service=identity_service,
        journey_service=CuratorGrowthJourneyService(identity_service=identity_service),
    )


@router.get(
    "",
    response_model=SuccessResponse[CuratorResourcesResponse],
    status_code=status.HTTP_200_OK,
    summary="Get Curator resource recommendations",
    responses={
        status.HTTP_404_NOT_FOUND: {
            "model": ErrorResponse,
            "description": "No Curator identity profile has been created yet.",
        },
        status.HTTP_503_SERVICE_UNAVAILABLE: {
            "model": ErrorResponse,
            "description": "The AI provider is temporarily unavailable.",
        },
    },
)
async def get_curator_resources(
    refresh: bool = Query(default=False),
    service: CuratorResourceService = Depends(get_curator_resource_service),
) -> SuccessResponse[CuratorResourcesResponse]:
    """Return persisted or freshly generated Curator Agent recommendations."""

    try:
        response = await run_in_threadpool(service.get_resources, refresh=refresh)
    except TransientLLMError as exc:
        logger.warning("Curator resources failed because Gemini is unavailable: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "message": "The AI service is temporarily unavailable. Please try again shortly.",
                "error_code": "LLM_UNAVAILABLE",
            },
        ) from exc
    except RuntimeError as exc:
        message = str(exc)
        if "Gemini API key" in message:
            logger.warning("Curator resources setup is incomplete: %s", exc)
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail={
                    "message": (
                        "Curator resources require a Gemini API key because "
                        "recommendations are generated by the Curator Agent."
                    ),
                    "error_code": "RESOURCES_SETUP_INCOMPLETE",
                },
            ) from exc
        raise
    if response is None:
        raise _not_found("Complete Curator onboarding before opening resources.")
    return SuccessResponse(message="Curator resources retrieved.", data=response)


@router.post(
    "/bookmark",
    response_model=SuccessResponse[CuratorResourceEngagementResponse],
    status_code=status.HTTP_200_OK,
    summary="Bookmark or unbookmark a Curator resource",
)
async def bookmark_curator_resource(
    request: CuratorResourceBookmarkRequest,
    service: CuratorResourceService = Depends(get_curator_resource_service),
) -> SuccessResponse[CuratorResourceEngagementResponse]:
    """Persist bookmark state for one resource."""

    response = await run_in_threadpool(
        service.set_bookmark,
        resource=request.resource,
        bookmarked=request.bookmarked,
    )
    if response is None:
        raise _not_found("Complete Curator onboarding before bookmarking resources.")
    return SuccessResponse(message="Resource bookmark updated.", data=response)


@router.post(
    "/open",
    response_model=SuccessResponse[CuratorResourceEngagementResponse],
    status_code=status.HTTP_200_OK,
    summary="Record a Curator resource open event",
)
async def open_curator_resource(
    request: CuratorResourceOpenRequest,
    service: CuratorResourceService = Depends(get_curator_resource_service),
) -> SuccessResponse[CuratorResourceEngagementResponse]:
    """Persist resource engagement analytics."""

    response = await run_in_threadpool(service.record_open, resource=request.resource)
    if response is None:
        raise _not_found("Complete Curator onboarding before opening resources.")
    return SuccessResponse(message="Resource engagement recorded.", data=response)


@router.put(
    "/preferences",
    response_model=SuccessResponse[CuratorResourcePreferences],
    status_code=status.HTTP_200_OK,
    summary="Update Curator resource preferences",
)
async def update_curator_resource_preferences(
    request: CuratorResourcePreferencesRequest,
    service: CuratorResourceService = Depends(get_curator_resource_service),
) -> SuccessResponse[CuratorResourcePreferences]:
    """Persist resource content preferences."""

    response = await run_in_threadpool(service.update_preferences, request)
    if response is None:
        raise _not_found("Complete Curator onboarding before updating preferences.")
    return SuccessResponse(message="Resource preferences updated.", data=response)


def _not_found(message: str) -> HTTPException:
    return HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail={"message": message, "error_code": "not_found"},
    )
