"""Schemas for persisted Curator growth journeys."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from backend.domains.curator.schemas.decision import Decision
from backend.domains.curator.schemas.identity import IdentityProfile
from backend.domains.curator.schemas.planner import GrowthPlan


ActivityStatus = Literal["locked", "available", "completed"]
PhaseStatus = Literal["completed", "current", "upcoming"]


class CuratorJourneyActivity(BaseModel):
    """One actionable activity in a Curator journey."""

    id: str = Field(..., min_length=3, max_length=120)
    task: str = Field(..., min_length=4, max_length=240)
    durationMinutes: int = Field(..., ge=5, le=180)
    status: ActivityStatus


class CuratorJourneyResource(BaseModel):
    """Resource category selected for the current journey phase."""

    title: str = Field(..., min_length=2, max_length=160)
    resourceType: str = Field(..., min_length=2, max_length=80)
    purpose: str = Field(..., min_length=8, max_length=240)


class CuratorJourneyPhase(BaseModel):
    """Planner phase enriched with Curator execution details."""

    phaseNumber: int = Field(..., ge=1)
    title: str = Field(..., min_length=4, max_length=160)
    weekRange: str = Field(..., min_length=2, max_length=80)
    summary: str = Field(..., min_length=8, max_length=500)
    status: PhaseStatus
    activities: list[CuratorJourneyActivity] = Field(..., min_length=1, max_length=12)
    resources: list[CuratorJourneyResource] = Field(default_factory=list, max_length=8)
    priorities: list[str] = Field(default_factory=list, max_length=8)


class CuratorJourneyAgentOutput(BaseModel):
    """Structured output generated by the Curator Agent."""

    phases: list[CuratorJourneyPhase] = Field(..., min_length=1, max_length=52)
    currentPhase: CuratorJourneyPhase
    todayActivity: CuratorJourneyActivity
    dailyActivities: list[CuratorJourneyActivity] = Field(..., min_length=1, max_length=12)
    currentPriorities: list[str] = Field(..., min_length=1, max_length=8)
    estimatedCompletion: str = Field(..., min_length=2, max_length=120)
    coachSummary: str = Field(..., min_length=20, max_length=1000)


class CuratorGrowthJourneyResponse(CuratorJourneyAgentOutput):
    """API response for the Growth Journey page."""

    identityProfileId: int
    identityProfile: IdentityProfile
    growthPlan: GrowthPlan
    decision: Decision
    progressPercentage: int = Field(..., ge=0, le=100)
