"""Schemas for Curator resource recommendations and engagement."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, field_validator


RESOURCE_TYPES = {"Book", "Video", "Podcast", "Article", "Community"}
ResourceType = str


class CuratedResource(BaseModel):
    """One personalized resource recommendation."""

    id: str
    title: str
    creator: str
    description: str
    tags: list[str] = Field(default_factory=list)
    estimatedDuration: str
    type: ResourceType
    url: str
    reason: str
    isBookmarked: bool = False
    viewedCount: int = Field(default=0, ge=0)

    @field_validator("tags")
    @classmethod
    def _clean_tags(cls, value: list[str]) -> list[str]:
        return [tag.strip()[:40] for tag in value if tag.strip()][:8]

    @field_validator("type")
    @classmethod
    def _validate_type(cls, value: str) -> str:
        stripped_value = value.strip().title()
        if stripped_value not in RESOURCE_TYPES:
            raise ValueError("Resource type must be Book, Video, Podcast, Article, or Community.")
        return stripped_value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value: str) -> str:
        stripped_value = value.strip()
        if not stripped_value.startswith(("https://", "http://")):
            raise ValueError("Resource URL must start with http:// or https://.")
        return stripped_value


class CuratedResourceAgentOutput(BaseModel):
    """Structured output generated by the Curator Agent for resources."""

    recommendationSummary: str
    selectionReasons: list[str] = Field(default_factory=list)
    resources: list[CuratedResource] = Field(default_factory=list)


class CuratorResourcePreferences(BaseModel):
    """User-editable resource preferences."""

    preferredTypes: list[ResourceType] = Field(default_factory=list)
    preferredTags: list[str] = Field(default_factory=list)

    @field_validator("preferredTags")
    @classmethod
    def _clean_preferred_tags(cls, value: list[str]) -> list[str]:
        return [tag.strip()[:40] for tag in value if tag.strip()][:12]


class CuratorResourcesResponse(CuratedResourceAgentOutput):
    """API response for the Curated Resources page."""

    identityProfileId: int = Field(..., gt=0)
    recommendationId: int = Field(..., gt=0)
    generatedAt: datetime
    preferences: CuratorResourcePreferences


class CuratorResourceBookmarkRequest(BaseModel):
    """Request to bookmark or unbookmark a resource."""

    resource: CuratedResource
    bookmarked: bool


class CuratorResourceOpenRequest(BaseModel):
    """Request to persist that a resource was opened."""

    resource: CuratedResource


class CuratorResourcePreferencesRequest(CuratorResourcePreferences):
    """Request to update Curator resource preferences."""


class CuratorResourceEngagementResponse(BaseModel):
    """Response after resource engagement changes."""

    resourceId: str
    isBookmarked: bool
    viewedCount: int = Field(..., ge=0)
